[server]
headless = true
port = ${PORT}
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#000000"

[general]
python_version = "3.10"
target = "app.py"
